name: scrape_cast

on:
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * 1"

jobs:
  run-scrape:
    runs-on: ubuntu-latest

    env:
      LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
      LINE_USER_ID: ${{ secrets.LINE_USER_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests beautifulsoup4

      - run: python scrape_cast.py
